### ISSUE TITLE
Write a comma before array item and delete splice method

### ISSUE THREAD

**Issue by CodeAcee** [whoisbroken/js-custom-methods#14]
https://github.com/whoisbroken/js-custom-methods/blob/9fc5916ef47dece1be24dfb16bc696d5d1664ad5/main.js#L155#L158

**Comment by CodeAcee** [comment]
You use a construction where you put a comma in
 at the end of the template string, to make this method easier, you can write a comma before the template literal and then you don't need the splice method

**Comment by whoisbroken** [comment]
for this case I need start my loop from 1 index.
I think its not big deal
